on:
  push
jobs:
  macos13:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper

      - name: Brew install base dependencies
        run: |
          # A workaround for "The `brew link` step did not complete successfully" error.
          brew install --quiet python@3 || brew link --overwrite python@3
          brew install qt@5
          brew install --quiet automake berkeley-db@4 miniupnpc gperf qrencode librsvg && curl -L https://raw.githubusercontent.com/vergecurrency/protobuf261/master/protobuf261.rb > protobuf261.rb && brew install protobuf261.rb
      
      - name: Brew install boost from our homebrew deps
        run: curl -LO https://archives.boost.io/release/1.65.1/source/boost_1_65_1.tar.bz2
        
      - name: tar boost
        run: tar -xvzf boost_1_65_1.tar.bz2
        
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_14.1.0.app/Contents/Developer'
      
      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4 boost1651
        
      - name: which clang/xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: ./configure --disable-tests --disable-dependency-tracking --disable-werror --with-gui --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: make
        run: make -j4

      - name: make .dmg
        run: make deploy

      - uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg