on:
  push
jobs:
  macos13:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: git config credential.helper
        run: git config credential.helper
        
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.1.0.app

      - name: Brew install base dependencies
        run: |
          # A workaround for "The `brew link` step did not complete successfully" error.
          brew install --quiet python@3 || brew link --overwrite python@3
          brew install qt@5
          brew install --quiet automake berkeley-db@4 miniupnpc gperf qrencode librsvg && curl -L https://raw.githubusercontent.com/vergecurrency/protobuf261/master/protobuf261.rb > protobuf261.rb && brew install protobuf261.rb
      
      - name: handle line endings
        run: git config --global core.autocrlf input
      
      - name: Download and extract Berkeley DB 4.8
        run: |
          wget https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
          tar -xzvf db-4.8.30.NC.tar.gz
          
      - name: Configure Berkeley DB 4.8
        run: cd db-4.8.30.NC/build_unix && ../dist/configure --enable-cxx
        
      - name: Fix atomic Berkeley DB compile bug
        run: |
          sed -i '' 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' db-4.8.30.NC/dbinc/atomic.h

      - name: Download Boost file
        run: wget https://archives.boost.io/release/1.65.1/source/boost_1_65_1.tar.bz2
      
      - name: Extract Boost file
        run: tar -xjvf boost_1_65_1.tar.bz2

      - name: Patch boost to use gcc-12
        run: |
          cd boost_1_65_1/ && sed -i '' -e '/darwin)/,/;;/c\    BOOST_JAM_CC=gcc-12' tools/build/src/engine/build.sh
          cd boost_1_65_1/ && sed -i '' -e '/toolset darwin cc : "-o "/,/;;/c\    toolset darwin gcc-12 : "-o " : -D' tools/build/src/engine/build.jam
          
      - name: bootstrap
        run: cd boost_1_65_1 && git branch && ./bootstrap.sh
      
      - name: b2
        run: cd boost_1_65_1 && ./b2 install

      
      
      - name: Brew link dependencies
        run: brew link qt@5 berkeley-db@4
        
      - name: which clang/xcode
        run: clang --version

      - name: Auto generate
        run: ./autogen.sh

      - name: configure
        run: CC=gcc-12 CXX=g++-12 OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lssl -lcrypto" ./configure --disable-tests --disable-dependency-tracking --disable-werror --with-gui --bindir=`pwd`/release/bin --libdir=`pwd`/release/lib

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
        
      - name: make
        run: make -j4

      - name: make .dmg
        run: make deploy

      - uses: actions/upload-artifact@v4
        with:
          name: tpay-macos13
          path: |
            *.dmg
