on:
  push

jobs:
  ubuntu20:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Update apt repos
        run: sudo apt-get update

      - name: Install base dependencies
        run: sudo apt-get install -y build-essential xutils-dev libicu-dev libtool gperf autotools-dev automake pkg-config bsdmainutils libattr1-dev make automake bison byacc cmake curl g++-multilib binutils-gold bison byacc python2

      - name: Build depends
        run: sudo apt-get install -y libssl-dev libevent-dev asciidoc zlib1g-dev libseccomp-dev libcap-dev libncap-dev obfs4proxy libminiupnpc-dev qt5-default
        
      - name: More depends
        run: sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqt5webkit5-dev libqt5webkit5
        
      - name: Download and extract Berkeley DB 4.8
        run: |
          wget https://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
          tar -xzvf db-4.8.30.NC.tar.gz

      - name: Configure Berkeley DB 4.8
        run: cd db-4.8.30.NC/build_unix && ../dist/configure --enable-cxx
        
      - name: Fix atomic Berkeley DB compile bug
        run: |
          sed -i 's/__atomic_compare_exchange/__atomic_compare_exchange_db/g' db-4.8.30.NC/dbinc/atomic.h

      - name: Build and install Berkeley DB 4.8
        run: cd db-4.8.30.NC/build_unix && make && sudo make install

      - name: Link Berkeley DB libraries
        run: |
          sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb-4.8.so /usr/lib/libdb-4.8.so
          sudo ln -s /usr/local/BerkeleyDB.4.8/lib/libdb_cxx-4.8.so /usr/lib/libdb_cxx-4.8.so

      - name: Download Boost file
        run: wget https://archives.boost.io/release/1.65.1/source/boost_1_65_1.tar.bz2
      
      - name: Extract Boost file
        run: tar -xjvf boost_1_65_1.tar.bz2
        
      - name: Configure and bootstrap Boost
        run: |
          cd boost_1_65_1
          ./bootstrap.sh --prefix=/usr/local --with-libraries=chrono,date_time,iostreams,filesystem,program_options,system,thread,test

      - name: Build and install Boost
        run: |
          cd boost_1_65_1
          sudo ./b2 install

      - name: Autogenerate TokenPay code
        run: ./autogen.sh

      - name: Configure TokenPay code
        run: |
          ./configure \
            CPPFLAGS="-I/usr/local/BerkeleyDB.4.8/include -O2" \
            LDFLAGS="-L/usr/local/BerkeleyDB.4.8/lib" \
            --enable-gui \
            --disable-bench \
            --disable-tests \
            --disable-dependency-tracking \
            --disable-werror \
            --prefix=$(pwd)/depends/x86_64-linux-gnu \
            --bindir=$(pwd)/release/bin \
            --libdir=$(pwd)/release/lib

      - name: Build wallet and daemon
        run: make -j4
      
      - uses: actions/upload-artifact@v4
        with:
          name: tpay-ubuntu20
          path: |
            ./src/tokenpayd
            ./src/tokenpay
